name: Update Nighteye CSS
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - '_layouts/all-html-elements.html'
jobs:
  Update-Nighteye:
    runs-on: ubuntu latest
    steps:
      - name: Send POST Request to Nighteye API
        id: postReqRes
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://service.nighteye.app/api/convert'
          method: 'POST'
          timeout: 15000
          data: '{"ac":"a","pl":{"urls":["https://droneuni.cf/all-html-elements/"]}}'
      - name: Show response
        run: echo ${{ fromJson(steps.myRequest.outputs.response).obj.[0] }}
